version: 2.1

jobs:
  # build:
  deploy:
    # machine:
    #   enabled: true
    # steps:
    #   - run:
    #       name: Deploy Over SSH
    #       command: |
    #         ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Stop
          command: |
            echo 'Stoping existing containers...'
            docker-compose stop
            docker-compose rm -v --force
      - run:
          name: Start
          command: |
            echo 'Starting Wordpress containers...'
            docker-compose up -d

workflows:
  version: 2
  wp-deploy:
    jobs:
      # - build
      - deploy:
          # requires:
          #   - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch